komuw/ong

CHANGELOG.md, main.go, server/server.go, server/server_test.go
fixes: https://github.com/komuw/goweb/issues/23
=> Issues/23: harmonize timeouts

CHANGELOG.md, LICENSE, README.md, errors/errors.go, errors/errors_test.go, handlers.go, log/log.go, log/log_test.go, main.go, middleware/auth.go, middleware/csrf.go, middleware/csrf_test.go, middleware/log.go, middleware/log_test.go, middleware/middleware.go, middleware/middleware_test.go, middleware/panic.go, middleware/security.go, server/server.go
fixes: https://github.com/komuw/goweb/issues/44
fixes: https://github.com/komuw/goweb/issues/43
fixes: https://github.com/komuw/goweb/issues/42
=> quality of life improvements

CHANGELOG.md, server/cert_test.go, server/pprof.go, server/pprof_test.go, server/server.go
fixes: https://github.com/komuw/goweb/issues/9
=> issues/9: expvar metrics

CHANGELOG.md, middleware/auth_test.go, middleware/cors_test.go, middleware/csrf_test.go, middleware/gzip_test.go, middleware/log.go, middleware/log_test.go, middleware/middleware_test.go, middleware/panic_test.go, middleware/ratelimiter.go, middleware/ratelimiter_test.go, middleware/redirect_test.go, middleware/security_test.go, server/pprof_test.go, server/server_test.go
fixes: https://github.com/komuw/goweb/issues/63
fixes: https://github.com/komuw/goweb/issues/62
=> issues/63: fix some races

CHANGELOG.md, README.md, example/main.go, server/server.go, server/server_test.go
fixes: https://github.com/komuw/ong/issues/73
=> issues/73: bind on 0.0.0.0 or localhost conditionally

CHANGELOG.md, example/main.go, middleware/redirect.go, middleware/redirect_test.go, server/server.go, server/server_test.go, server/tls_conf.go
fixes: https://github.com/komuw/ong/issues/72
=> issues/72: redirect IP to domain

CHANGELOG.md, example/main.go, middleware/csrf.go, middleware/csrf_test.go
fixes: https://github.com/komuw/ong/issues/76
=> issues/76: dont require csrf for post requests that have no cookies AND no HTTP authentication

CHANGELOG.md, example/main.go, middleware/gzip.go, middleware/gzip_test.go
fixes: https://github.com/komuw/ong/issues/81
=> issues/81: handle gzip error

CHANGELOG.md, go.mod, go.sum, middleware/middleware.go, middleware/middleware_test.go
- it is slow
fixes: https://github.com/komuw/ong/issues/85
=> issues/85: disable gzip

CHANGELOG.md, xcontext/xcontext.go, xcontext/xcontext_test.go
What:
- Add an xcontext package
Why:
- Fixes: https://github.com/komuw/ong/issues/108
=> Add an xcontext package

CHANGELOG.md, README.md, enc/enc.go, enc/enc_test.go, enc/example_test.go, example/main.go, middleware/csrf.go, middleware/csrf_test.go, middleware/middleware.go, server/server_test.go
What:
- use key derivation in the `enc` ecryption/decryption package
Why:
- added security?
=> use key derivation in the `enc` ecryption/decryption package

CHANGELOG.md, client/client.go, client/client_test.go, client/example_test.go
What:
- add a http client
Why:
- Fixes: https://github.com/komuw/ong/issues/98
=> Issues/98: add a http client

CHANGELOG.md, cookie/cookie.go, cookie/cookie_test.go, cry/enc.go
What:
- add secure/encrypted cookies
Why:
- Fixes: https://github.com/komuw/ong/issues/31
=> issues/31: add secure/encrypted cookies

CHANGELOG.md, README.md, example/main.go, mux/example_test.go, mux/mux.go, mux/mux_test.go, mux/route.go, mux/route_test.go, server/example_test.go, server/server_test.go
What:
- add ability to specify a custom 404 handler
Why:
- Fixes: https://github.com/komuw/ong/issues/153
=> issues/153: add ability to specify a custom 404 handler

CHANGELOG.md, mux/mux.go, mux/mux_test.go, mux/route.go, mux/route_test.go
What:
- Bugfix: When a route conflict is detected, report the correct file & line number.
Why:
- Fixes: https://github.com/komuw/ong/issues/158
=> issues/158: when a route conflict is detected, report the correct file & line number

CHANGELOG.md, id/id.go, id/id_test.go, middleware/csrf_test.go
- Fixes: https://github.com/komuw/ong/issues/191
=> issues/191: ong/id should generate strings of the exact requested length

CHANGELOG.md, log/log.go, log/log_test.go
- Fixes: https://github.com/komuw/ong/issues/190
=> issues/190: do not quote special characters

CHANGELOG.md, middleware/session.go, middleware/session_test.go
- Unfortunately, we could not come up with a test for it. Even without the fix, the tests were saying that there's only one cookie.
- Fixes: https://github.com/komuw/ong/issues/205
=> issues/205: do not duplicate session cookies

CHANGELOG.md, go.mod, go.sum, log/log.go, log/log_test.go, middleware/loadshed.go, middleware/ratelimiter.go
Why:
- Udates: https://github.com/komuw/ong/issues/182
=> issues/182: update to latest slog changes

.github/workflows/ci.yml, .github/workflows/integration_test_coverage.sh, .gitignore, CHANGELOG.md, middleware/loadshed.go, middleware/loadshed_test.go
Updates: https://github.com/komuw/ong/issues/231
=> issues/231: better loadshed calculations

.github/workflows/integration_test_coverage.sh, CHANGELOG.md, example/handlers.go
- Updates: https://github.com/komuw/ong/issues/231
=> issues/231: update loadtest

CHANGELOG.md, client/client.go, go.mod, go.sum, log/log.go, log/log_test.go, middleware/log.go, middleware/recoverer.go
- Updates; https://github.com/komuw/ong/issues/182
=> issues/182: Update to latest exp/slog

CHANGELOG.md, server/tls_conf.go
add a http timeout when calling ACME for certificates
=> acme-timeout

CHANGELOG.md, example/handlers.go, example/main.go, server/cert.go, server/pprof.go, server/server.go
- Fixes: https://github.com/komuw/ong/issues/274
=> issues/274: bugfix; match number of log arguments

CHANGELOG.md, internal/acme/acme.go, internal/acme/acme_test.go
- Fixes: https://github.com/komuw/ong/issues/305
=> issues/305: Refuse to fetch certificates for IP addresses

CHANGELOG.md, middleware/log.go
- Updates: https://github.com/komuw/ong/issues/324
=> issues/324: Fix logging of ratelimited/loadshedded requests

CHANGELOG.md, server/server.go, server/tls_conf.go, server/tls_conf_test.go
- Fixes: https://github.com/komuw/ong/issues/333
=> issues/333: Add ability to use mutual TLS authentication

CHANGELOG.md, server/server.go
- Bugfix for https://github.com/komuw/ong/pull/334
- Updates: https://github.com/komuw/ong/issues/333
=> issues/333: bugfix, add ability to use mutual TLS authentication

CHANGELOG.md, example/main.go, internal/key/key.go, internal/key/key_test.go, middleware/auth.go, middleware/auth_test.go, middleware/gzip.go, middleware/log.go, middleware/middleware.go, middleware/session.go, mux/mux_test.go
- Updates: https://github.com/komuw/ong/issues/92
- This still doesn't fix the issue, there is still https://github.com/komuw/ong/pull/213 for that
=> issues/92: Add support for http.NewResponseController

CHANGELOG.md, middleware/csrf.go, middleware/csrf_test.go, middleware/middleware.go, middleware/middleware_test.go, middleware/session.go, middleware/session_test.go, mux/mux.go, mux/route.go
- Add String and GoString methods. This helps to mask/redact sensitive items like secretKeys when printing
=> Improve formatting of some types

CHANGELOG.md, middleware/security.go
- The previous policy was preventing media files from been served in localhost
=> Add 'self' to CSP policy

CHANGELOG.md, README.md, config/cert.go, config/config.go, config/config_test.go, config/example_test.go, internal/acme/acme.go, internal/acme/acme_test.go, internal/acme/helpers.go, internal/acme/helpers_test.go, middleware/middleware_test.go, server/example_test.go, server/tls_conf.go, server/tls_conf_test.go
- Fixes: https://github.com/komuw/ong/issues/400
=> issues/400: Add ability to specify the exact domains to use for TLS as well as wildcards.

CHANGELOG.md, internal/acme/helpers.go
- Fixes: https://github.com/komuw/ong/issues/403
=> acme: Do not create certificate directory unless certificate fetch succeeded 

CHANGELOG.md, middleware/redirect.go, middleware/redirect_test.go
- Fixes: https://github.com/komuw/ong/issues/405
=> issues/405: a http subdomain should be redirected to the same subdomain at https.

CHANGELOG.md, id/uuid_test.go
- Fixes: https://github.com/komuw/ong/issues/396
=> issues/396: add tests for uuid8 sortable
