komuw/ong

- CHANGELOG.md
- middleware/panic.go
- middleware/panic_test.go
fixes: https://github.com/komuw/goweb/issues/12
> issues/12: panic middleware

- CHANGELOG.md
- server/pprof.go
- server/pprof_test.go
- server/server.go
- server/server_test.go
fixes: https://github.com/komuw/goweb/issues/65
> issues/65: resuse address/port for pprof and redirect servers

- CHANGELOG.md
- README.md
- example/main.go
- server/server.go
- server/server_test.go
- server/tls_conf.go
fixes: https://github.com/komuw/ong/issues/78
> issues/78: remove http

- CHANGELOG.md
- errors/errors.go
Instead of using `stack []uintptr` to represent an errors stacktrace,
use `stack [4]uintptr` instead.
This idea is taken from golang/xerrors.
see: https://github.com/golang/xerrors/blob/65e65417b02f28de84b55f16b46a1e789149973a/frame.go#L13-L16
> efficient-err-stack

- CHANGELOG.md
- server/automaxmem/automaxmem.go
- server/automaxmem/automaxmem_test.go
- server/server.go
What:
- automatically set GOMEMLIMIT in container environments
Why:
- Fixes: https://github.com/komuw/ong/issues/100
- This is similar in spirit to go.uber.org/automaxprocs/maxprocs
> automatically set GOMEMLIMIT in container environments

- CHANGELOG.md
- middleware/csrf.go
- middleware/csrf_test.go
- middleware/log.go
- middleware/secret.go
What:
- When a request fails csrf validation, redirect it to the same url using http GET
Why:
- It seems like it would make for a more intuitive customer experience.
- Fixes: https://github.com/komuw/ong/issues/114
> Issues/114: redirect csrf failures to same url

- .github/workflows/ci.yml
- CHANGELOG.md
- client/client.go
- client/client_test.go
What:
- Replace use of net.Ip with net/netip
Why:
- Fixes: https://github.com/komuw/ong/issues/129
> issues/129: Replace use of net.Ip with net/netip

- CHANGELOG.md
- cry/enc.go
- cry/enc_test.go
- cry/example_test.go
- cry/hash.go
- cry/hash_test.go
- middleware/csrf.go
- middleware/csrf_test.go
What:
- Add password hashing capabilities.
Why:
- Fixes: https://github.com/komuw/ong/issues/133
> issues/133: Add password hashing capabilities.

- automax/automaxmem.go
- automax/automaxmem_test.go
On an ubuntu 20.04 system (cgroupv1 system), `SetMem` failed silently to parse the limit from the cgroup file. This is because the file contents actually end with a newline character, that leads `strconv.ParseInt` to fail. Updated the test fixture accordingly.
I did not test on a cgroupv2 system, but my experience is that all these files end with a newline anyway, so I put the `strings.TrimSpace` in the common code path to be sure.
> Fix automax.SetMem on cgroupv1 systems

- CHANGELOG.md
- mux/route.go
- mux/route_test.go
What:
- fix false positive/negative/whatever route conflict
Why:
- Fixes: https://github.com/komuw/ong/issues/156
> issues/156: fix false positive/negative/whatever route conflict

- CHANGELOG.md
- middleware/panic.go
- middleware/panic_test.go
What:
- Panic middleware should include correct stack trace.
Why:
- Fixes: https://github.com/komuw/ong/issues/162
> issues/162: Panic middleware should include correct stack trace.

- CHANGELOG.md
- middleware/log.go
- middleware/log_test.go
- middleware/panic.go
What:
- log client address without port
Why:
- Fixes: https://github.com/komuw/ong/issues/163
> issues/163: log client address without port

- CHANGELOG.md
- sess/sess.go
What:
- Set session cookie only if non-empty
- I was unable to add a testcase, but I did test manually and it seems okay
Why:
- Fixes: https://github.com/komuw/ong/issues/169
> issues/169: Set session cookie only if non-empty

- CHANGELOG.md
- example/main.go
- middleware/middleware.go
- middleware/reload_protect.go
- middleware/reload_protect_test.go
- middleware/session_test.go
What:
- Add a middleware that attempts to provides protection against a form re-submission when a user reloads/refreshes an already submitted web page/form.
If such a situation is detected; this middleware will issue a http GET redirect to the same url.
Why:
- Fixes: https://github.com/komuw/ong/issues/168
> issues/168: Add ReloadProtector middleware

- CHANGELOG.md
- example/main.go
- mux/mux.go
- mux/mux_test.go
What:
-  mux.NewRoute should panic if handler is already wrapped in a ong/middleware 
Why:
- Fixes: https://github.com/komuw/ong/issues/167
> issues/167:  NewRoute should panic if handler is already wrapped in a ong/middleware 

- .github/workflows/ci.yml
- CHANGELOG.md
- client/client.go
- client/client_test.go
- client/example_test.go
What:
- Use roundTripper for logging
Why:
- Fixes: https://github.com/komuw/ong/issues/184
> issues/184: Use roundTripper for logging

- CHANGELOG.md
- middleware/cors.go
- middleware/cors_test.go
- middleware/csrf.go
- middleware/csrf_test.go
- middleware/example_test.go
- middleware/gzip.go
- middleware/gzip_test.go
- middleware/loadshed.go
- middleware/loadshed_test.go
- middleware/log.go
- middleware/log_test.go
- middleware/middleware.go
- middleware/panic.go
- middleware/panic_test.go
- middleware/ratelimiter.go
- middleware/ratelimiter_test.go
- middleware/redirect.go
- middleware/redirect_test.go
- middleware/reload_protect.go
- middleware/reload_protect_test.go
- middleware/security.go
- middleware/security_test.go
- middleware/session.go
- middleware/session_test.go
- sess/example_test.go
- sess/sess.go
What:
- make most middleware private
Why:
- Ideally we should only use the `middleware.Get`, `middleware.Post`, etc middlewares
> make most middleware private

- CHANGELOG.md
- client/client.go
- example/main.go
- log/log.go
- middleware/log.go
- server/cert.go
- server/cert_test.go
- server/example_test.go
- server/server.go
- server/server_test.go
Imagine;
```go
l := log.New(w, 10)
fmt.Println(l.logId)
ctx := context.Background()
l2 := l.WithCtx(ctx)
fmt.Println(l.logId)
```
Previously, this would print two different logId's. This is because `WithCtx` would try to fetch a logId from `ctx` and if it can't, it would generate a new one.
In this PR, `WithCtx` does the same; but if `ctx` has no logId, then it re-uses the logId from `l`
> ong/log: WithCtx should only use the id from context, if that ctx actually contains an Id

- CHANGELOG.md
- errors/errors.go
- errors/errors_test.go
Given;
```go
func a() error { 
_, err := os.ReadFile("/non/existent.txt")  // line 2
return errors.Wrap(err)                            // line 3
}
func b() error { return a() }                           // line 5
func c() error { return b() }                           // line 6
func main() {
err := errors.Wrap(c())                            // line 9
fmt.Printf("%+#v",  err)
}
```
This should print the whole stack trace starting with the line 9, line 6, .... line 3
- Fixes: https://github.com/komuw/ong/issues/197
> issues/197: ong/errors; wrap as deep as possible

- CHANGELOG.md
- errors/errors.go
- errors/errors_test.go
- errors/example_test.go
- id/example_test.go
- Usage;
```go
func fetchUser(u string) (errp error) {
defer errors.Dwrap(&errp)
users := []string{"John", "Alice", "Kamau"}
if !slices.Contains(users, u) {
return fmt.Errorf("user %s not found", u)
}
return nil
}
e := fetchUser("Emmy")
fmt.Printf("%+#v", e)
```
- Fixes: https://github.com/komuw/ong/issues/198
- Inspired by https://github.com/golang/pkgsite/blob/035bfc02f3faa0221e0edf90b0a21d3619c95fdd/internal/derrors/derrors.go#L212-L237
> issues/198: Add errors.Dwrap

- CHANGELOG.md
- id/id.go
- id/id_test.go
This occurred beause; https://github.com/komuw/ong/blob/1e8c51c371cb5888422de891085af87a3d0adb79/id/id.go#L46 does not produce a whole integer always;
```go
>>> n=301
>>> ((((n * 6) - 5) / 8) + 1)
226.125
```
> ong/id: fix bug where strings were not of specified length

- CHANGELOG.md
- client/client.go
- Use net.Dialer.ControlContext instead of use net.Dialer.Control
Using Dialer.ControlContext instead of Dialer.Control allows;
- propagation of logging contexts, metric context or other metadata down to the callback.
- cancellation if the callback potentially does I/O.
- Fixes: https://github.com/komuw/ong/issues/149
- https://github.com/golang/go/issues/55301
> issues/149: use net.Dialer.ControlContext

- .github/workflows/ci.yml
- CHANGELOG.md
- id/id.go
- Fixes: https://github.com/komuw/ong/issues/211
- Fixes: https://github.com/komuw/ong/issues/210
> issues/211: re-enable golangci-lint

- .github/workflows/ci.yml
- CHANGELOG.md
- example/main.go
- log/log.go
- middleware/loadshed.go
- middleware/loadshed_test.go
- middleware/log.go
- middleware/recoverer.go
- Fixes: https://github.com/komuw/ong/issues/217
> issues/217: loadshedder should not re-order latencies.

- .github/workflows/ci.yml
- CHANGELOG.md
- server/cert.go
- server/cert_test.go
- server/server.go
- server/server_test.go
What:
- Create dev certs only if they do not exists or are expired.
Why:
- Fixes: https://github.com/komuw/ong/issues/223
> issues/223: create dev certs if do not exists or expired

- CHANGELOG.md
- client/client.go
- client/client_test.go
- errors/example_test.go
- example/handlers.go
- internal/README.md
- internal/ctx/ctx.go
- log/log.go
- log/log_benchmarks_test.go
- log/log_test.go
- middleware/csrf.go
- middleware/csrf_test.go
- middleware/log.go
- middleware/log_test.go
- middleware/middleware_test.go
- middleware/recoverer.go
- middleware/recoverer_test.go
- middleware/reload_protect.go
- middleware/session_test.go
- middleware/trace_test.go
- mux/mux.go
- mux/mux_test.go
- server/cert_test.go
- server/pprof.go
- server/pprof_test.go
- server/server_test.go
- sess/sess.go
- The organization should be;
```
stdlib imports
ong imports
third party imports
```
> organise imports

- CHANGELOG.md
- cookie/cookie.go
- internal/clientip/client_ip.go
- internal/finger/finger.go
- middleware/fingerprint.go
- middleware/ratelimiter_test.go
- server/server_test.go
**What:**
- This helps to try and mitigate against session replay attacks and session hijacking.
Two motivating examples:
(a) CircleCI was hacked[1]. They said; "Our investigation indicates that the malware was able to execute session cookie theft, enabling them to impersonate the targeted employee in a remote location"
(b) Loom had an incident[2]. They said; "Some our users had their information exposed to other user accounts. A configuration change to our Content Delivery Network (CDN) caused incorrect session cookies to be sent back to our users."
- In both the two cases I do believe that including the client's IP address could have helped mitigate the issue. We already do include user IP addresses in encrypted cookies.
- The problem with client IP is that they can be spoofed[3]
- I do …
> issues/249: Include TLS fingerprint in encrypted cookies

- CHANGELOG.md
- internal/clientip/client_ip.go
- internal/clientip/client_ip_test.go
- middleware/client_ip.go
- middleware/client_ip_test.go
- middleware/example_test.go
- middleware/middleware.go
- server/server.go
Sometimes a server is placed behind a TCP proxy. 
That server thus never gets the actual client IP.
The proxy protocol[1] fixes that issue by carrying connection information across proxies inside the `PROXY` header.
- Fixes: https://github.com/komuw/ong/issues/253
1. https://www.haproxy.org/download/2.8/doc/proxy-protocol.txt
> issues/253: add support for PROXY protocol in clientIP

- CHANGELOG.md
- server/server.go
- server/server_test.go
Gracefully handle application termniation in kubernetes.
If your app is running in kubernetes(k8s), if a pod is deleted;
(a) it gets deleted from service endpoints.
(b) it receives a SIGTERM from kubelet.
(a) & (b) are done concurrently. Thus (b) can occur before (a);
If that is the case; your app will shutdown while k8s is still sending traffic to it.
We add a sleep before calling server.Shutdown to try and minimize the duration of that race condition.
1. https://twitter.com/thockin/status/1560398974929973248
2. https://twitter.com/ProgrammerDude/status/1660238268863066114
> Gracefully handle application termniation in kubernetes

- CHANGELOG.md
- mux/example_test.go
- mux/mux.go
- mux/mux_test.go
- mux/route.go
What:
- Add mux Resolve function
- Imagine a customer calls and says they tried to access the url `https://localhost/check/888`, they expected to see a photo of a shark instead they saw a photo of an egg. How do you know which code/handler you should go look at, out of 10_000 handlers?
-  It is inspired by django's resolve url utility[3].
Why:
1. Fixes: https://github.com/komuw/ong/issues/267
2. This enhances debugging.
3. https://docs.djangoproject.com/en/4.2/ref/urlresolvers/#django.urls.resolve
> issues/267: add mux Resolve function

- CHANGELOG.md
- middleware/middleware.go
- middleware/middleware_test.go
- middleware/redirect.go
- middleware/redirect_test.go
- DNS rebinding[2] is a method of manipulating resolution of domain names that is commonly used as a form of computer attack.
The stdlib `http.ServeMux` does optionally protect against this class of attack[3][4][5]
- In our implementation, we fail the requests with a http 400 and appropriate error message if the incoming host is not equal to(or a subdomain) of the registered domain.
- We also update the middleware `New` function so that it panics if the given domain is invalid.
1. Fixes: https://github.com/komuw/ong/issues/260
2. https://en.wikipedia.org/wiki/DNS_rebinding
3. https://github.com/golang/go/blob/go1.20.5/src/net/http/request.go#L232-L236
4. https://github.com/golang/go/blob/go1.20.5/src/net/http/server.go#L2467
5. https://github.com/golang/go/blob/go1.20.5/src/net/http/server …
> issues/260: Add protection against DNS rebinding attacks.

- CHANGELOG.md
- client/client.go
- Fixes: https://github.com/komuw/ong/issues/285
> issues/285: Improve timeouts

- CHANGELOG.md
- server/server.go
- server/tls_conf.go
- Use one server to handle ACME challenge requests and normal application requests.
Prior to this, we had an app server and an ACME server that were both listening on the same port.
This used to cause the two to clash since requests for one might end up been handled by http handlers for the other.
- Fixes: https://github.com/komuw/ong/issues/284
> issues/284: Use one server for ACME and app

- CHANGELOG.md
- internal/acme/acme.go
- internal/acme/client.go
- internal/acme/helpers.go
- internal/acme/http_client.go
- server/server_test.go
- The issue is that the checklocks analyzer cannot tell that the following code is safe;
```go
package main
import "sync"
var mu sync.Mutex
func cool() string {
mu.Lock()
defer mu.Unlock()
defer func() {
_ = 90
}()
return "jj"
}
func main() {
cool()
}
```
See[2]. So we have to add an indirection to make that static analyzer happy.
1. Fixes: https://github.com/komuw/ong/issues/297
2. https://github.com/google/gvisor/tree/release-20230627.0/tools/checklocks#anonymous-functions-and-closures
> Work around bug in checklocks static analyzer

- CHANGELOG.md
- internal/acme/client_test.go
- middleware/log.go
- middleware/middleware_test.go
- When `http.ResponseWriter.WriteHeader()` is called more than once, it always produces the error;
`http: superfluous response.WriteHeader call from github.com/komuw/ong/middleware.(*logRW).WriteHeader (log.go:121)`
And the stack trace always points to the ong log middleware. But that does not mean that ong has any issues.
That error is always produced irrespective of if `ong` is used. It's how `net/http` works[2]
- Also note that; if `http.ResponseWriter.WriteHeader` is not called explicitly, the first call to Write
will trigger[3] an implicit WriteHeader(http.StatusOK).
- So this PR does not fix the issue(since it is an actual feature of `net/http`), rather it clarifies that understanding.
1. Fixes: https://github.com/komuw/ong/issues/48
2. …
> issues/48: Fix superfluous response.WriteHeader call

- CHANGELOG.md
- internal/acme/acme.go
- internal/acme/acme_test.go
- internal/acme/helpers.go
- internal/acme/helpers_test.go
- Updates: https://github.com/komuw/ong/issues/296
> issues/296: Tighten check cert validity script

- CHANGELOG.md
- internal/acme/acme.go
- server/tls_conf.go
- Before(due to a feature misuse bug), certificates would be fetched from disk for each request.
- Fixes: https://github.com/komuw/ong/issues/296
> issues/296: Fix bug where acme certificates were not cached in memory

- CHANGELOG.md
- internal/acme/client.go
- internal/acme/helpers.go
-This will limit possibility of denial of service.
- Fixes: https://github.com/komuw/ong/issues/320
> issues/320: Limit size of certificate allowed for download

- .github/workflows/ci.yml
- CHANGELOG.md
- id/id.go
- id/uuid.go
- It was confusing whether `id.New()` could be used for cryptography purposes.
> ong/id: Do not use crypto/rand

- CHANGELOG.md
- internal/acme/acme.go
- internal/acme/acme_test.go
- middleware/redirect.go
- Fixes: https://github.com/komuw/ong/issues/327
> issues/327: Bugfix, fetch certficate for subdomain beginning with number.

- CHANGELOG.md
- middleware/security.go
- middleware/security_test.go
- The recomended minimum value strict-transport-security is 30days
- Content-Security-Policy should be in one line else it does not show up
> Update security headers

- CHANGELOG.md
- middleware/redirect.go
- middleware/redirect_test.go
- This is what example.com and google.com does.
- This also means that we also do not have to pollute logs with it; https://github.com/komuw/ong/blob/46c45d146b6f7277922413fc30de1e4f34f2383c/middleware/log.go#L65-L72
- Fixes: https://github.com/komuw/ong/issues/341
> issues/341: Return http 404 instead of 400 for bad host header

- CHANGELOG.md
- README.md
- example/main.go
- mux/example_test.go
- mux/mux.go
- mux/mux_test.go
- server/example_test.go
- server/server_test.go
- The muxer did not need the logger
- Also rename mux.Mux to mux.Muxer. This reduces some stuttering.
> Remove logger from mux

- CHANGELOG.md
- config/config.go
- config/config_test.go
- middleware/middleware.go
- This is needed to try and prevent inadvertent logging/printing of the secure key
> Add config.secureKey

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- config/config.go
- config/config_test.go
- config/example_test.go
- cry/enc.go
- cry/example_test.go
- example/integration_test.go
- example/main.go
- internal/mx/mx_test.go
- internal/tst/tst.go
- log/log.go
- middleware/auth.go
- middleware/auth_test.go
- middleware/example_test.go
- middleware/middleware.go
- mux/example_test.go
- server/example_test.go
- server/pprof.go
- server/pprof_test.go
- server/server.go
- sess/example_test.go
- Fixes: https://github.com/komuw/ong/issues/366
> issues/366: Serve pprof using the same server as the application

- CHANGELOG.md
- middleware/middleware.go
- middleware/middleware_test.go
- middleware/trace.go
- middleware/traversal.go
- middleware/traversal_test.go
- Fixes: https://github.com/komuw/ong/issues/381
> issues/381: Try and prevent path traversal attacks

- CHANGELOG.md
- config/config.go
- config/config_test.go
- config/example_test.go
- cookie/cookie.go
- cookie/cookie_test.go
- internal/octx/octx.go
- middleware/middleware.go
- middleware/middleware_test.go
- middleware/session.go
- middleware/session_test.go
- sess/sess.go
- sess/sess_test.go
- Previously when validating encrypted cookies, we would compare the IP address(and TLS fingerprint) in the coming request to the one in the cookie.    
This meant that if someone moves from wifi internet to phone internet(as an example), their IP changes and thus their cookie/session would be invalid.
- Since the feature is useful in trying to mitigate against replay attacks(see: https://github.com/komuw/ong/issues/144), we instead introduce functionality that would allow users of `ong` to set whatever value they want as their anti replay data.  
So someone could set the IP + geo-location of the request as the anti replay data, and if either of those change; the cookies are invalid.
- Fixes: https://github.com/komuw/ong/issues/365
> issues/365: Do not use IP address and TLS fingerprint to validate cookies by default.

- CHANGELOG.md
- example/handlers.go
- sync/borrowed_test.go
- sync/example_test.go
- sync/sync.go
- This has a more intuitive Waitgroup.
```go
import "github.com/komuw/ong/sync"
wg, ctx := sync.New(context.Background(), 2)
_ = ctx
err := wg.Go(
func() error {
return nil
},
)
_ = err
```
> Add sync package

- .github/workflows/ci.yml
- CHANGELOG.md
- middleware/loadshed.go
- Ignore pprof endpoints when calculating latencies that inform load shedding decision.
> Do not loadshed based on latency from pprof endpoints

- CHANGELOG.md
- internal/acme/acme_test.go
- internal/tst/tst.go
- log/log_benchmarks_test.go
- log/log_test.go
- middleware/loadshed.go
- middleware/loadshed_test.go
- middleware/log.go
- Fixes: https://github.com/komuw/ong/issues/342
> Replace math/rand with math/rand/v2

- CHANGELOG.md
- id/id.go
- id/id_test.go
Use a simpler id generation algorithm
```
benchmark:
old-one  465.3 ns/op	 3 allocs/op
new-one  206.2 ns/op	 2 allocs/op
```
- FIxes: https://github.com/komuw/ong/issues/414
- Updates: https://github.com/komuw/ong/pull/409
- Relation: https://github.com/komuw/ong/commit/ed0f7fd10a85d26d953e61f21c91b4eeaf0851ce
- Inspired by: https://github.com/asggo/random
> issues/414: improve id generation

- CHANGELOG.md
- internal/acme/acme.go
- internal/acme/acme_test.go
- internal/acme/client_test.go
- Bugfix: Use the right token when verifying challenge token.
This is take II of https://github.com/komuw/ong/pull/439. In that PR we had made it so that when ACME wants to verify a challenge, we would respond with 404 if the token differs with what we have on file. The problem is that in that PR we were assuming that the token on file has same format as the one ACME calls us with. That is not the case and this PR attempts to fix that.
- Fixes: https://github.com/komuw/ong/issues/421
> issues/421: Use the right token when verifying challenge token

- CHANGELOG.md
- errors/errors.go
- errors/errors_test.go
- errors/join.go
- errors/stdlib.go
- When errors would get passed to `fmt.Errorf`, they would loose their traces.
This is an issue even with other third party error packages, see linked issue for examples.
Note; you have to use `errors.Errof` instea of `fmt.Errorf`
- Fixes: https://github.com/komuw/ong/issues/451
> issues/451: errors; retain stack traces when errors are wrapped with fmt

- CHANGELOG.md
- example/main.go
- internal/mx/mx_test.go
- middleware/auth.go
- middleware/auth_test.go
- server/server.go
- This was failing in mobile browsers. They were unable to show the username/password popup.
I suspect that those clients only expect a header of the form `www-authenticate: Basic realm=realmStr`. 
Where `realmStr` is a string with no special characters. The docs say that `realmStr` is any string whose character set is `us-ascii`. The `:` colon symbol is part of us-ascii(number 58). So I don't know why it would cause mobile clients to fail.
- Fixes: https://github.com/komuw/ong/issues/456
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate#realm
> issues/456: basicAuth; do not show hint

- CHANGELOG.md
- config/config.go
- config/config_test.go
- config/example_test.go
- middleware/session.go
- middleware/session_test.go
- Doing is so, would enable people to mutate that request.
- Somehow tangentially related; https://jub0bs.com/posts/2023-02-08-fearless-cors/#do-not-support-custom-callbacks
> AntiReplay function should not take a pointer to request

- CHANGELOG.md
- cry/enc.go
- cry/example_test.go
- cry/hash.go
- cry/hash_test.go
- example/handlers.go
- Latacora now recommends argon2id instead of scrypt
https://www.latacora.com/blog/2024/07/29/crypto-right-answers-pq/
> Replace scrypt with argon2id

- CHANGELOG.md
- config/config.go
- config/config_test.go
- config/example_test.go
- middleware/log.go
- middleware/recoverer.go
- Doing so risks the app developers mutating the response in unwanted ways.
Logging functionality has no business mutating responses or requests.
> ong/middleware: logFunc should not be passed a http.ResponseWriter

- internal/mx/mx_test.go
- internal/mx/route.go
- Fixes: https://github.com/komuw/ong/issues/480
- This allows someone to add a route that will handle all request paths
```go
rt, err := NewRoute("/*", "GET", someHandler(msg))
mux, err := New(opts, nil, rt)
```
That will be able to handle requests for `/`, `/hello`, `/he/okay/poor`
I've released `v0.1.12-beta` for testing.
> issues/480: mux; add flexible pattern
